global:
    scrape_interval:     15s
    evaluation_interval: 15s
scrape_configs:
  - job_name: metricas
    scrape_interval:     1s
    metrics_path: /metrics
    static_configs:
      - targets:
          - "acd34c2a5542:80"
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"