apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: metrica-svc
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: metrica 
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31773