global:
scrape_configs:
  - job_name: metricas
    scrape_interval: 1s
    static_configs:
      - targets:
          - "22c96110b162:80"
  - job_name: "prometheus"
    static_configs:
      - targets:
          - "localhost:9090"



